Feature/chatbot
DimaChuychenko/NIX_java_education_Chuychenko_Dima pull request #2
Opened 2021-11-04 21:30 UTC by DimaChuychenko

2021-11-06 10:27 UTC, maxsomochkin requested changes

2021-11-06 10:27 UTC, maxsomochkin commented on src/nix/education/java/chatbot/ChatBot.java
> +        while (answer != 2);
замени while(true); - у тебя уже есть условие выхода

2021-11-06 20:51 UTC, asrubel reviewed
Привет, в цикле у тебя уже есть выход, коммиты не сжал - занчит ребейс не делал

2021-11-09 23:53 UTC, asrubel approved these changes

2021-11-11 12:54 UTC, merged